- name: installation des serveurs web
  hosts: web
  remote_user: root

  tasks: 
    - name: Installation de git
      apt: name=git update_cache=yes
    - name: Installation de vim
      apt: name=vim 